/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BugTracker;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.security.SecureRandom;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.plaf.UIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author malla
 */
public class ReviewerUI extends javax.swing.JFrame {
    public TableCellRenderer align = new TextTableAlign();
    private ArrayList <BugReport> bugReportList = new ArrayList<BugReport>();
    private static String name;
    private static String id;
    ReportBugUI user = new ReportBugUI(name, id);
    /**
     * Creates new form HomePage
     */
    public ReviewerUI()
    {
        
    }
    public ReviewerUI(String name, String id) {
        initComponents();
        this.name = name;
        this.id = id;
        AccountNameField.setText(name);
        /*
        HeaderRenderer header = new HeaderRenderer(jTable1.getTableHeader().getDefaultRenderer());
        TableColumnModel columnModel = jTable1.getColumnModel();
        int HeaderCount = jTable1.getColumnCount();
        for(int i = 0; i < HeaderCount; i++)
        {
            columnModel.getColumn(i).setHeaderRenderer(header);
        }   
        */
        //jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        setTable1Settings();
        user.readBugList(model, bugReportList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoutButton = new javax.swing.JButton();
        ReportBugButton = new javax.swing.JButton();
        BugsWithPatches = new javax.swing.JButton();
        AccountNameField = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        HomeButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        jComboBoxSearch = new javax.swing.JComboBox();
        SearchButton = new javax.swing.JButton();
        ViewBugButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        TestPatchButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ReportBugTitleField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ReportBugIDField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportBugSummaryField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReportBugDescField = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        SubmitBugButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        ReportDateField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        ReportBugKeywordField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        CommentButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BugIDdetails = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BugTitleDetails = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BugReporterDetails = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AssigneeDetails = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DescDetails = new javax.swing.JTextArea();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        SumDetails = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        TestResultsDetails = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ReviewerDetails = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        PatchNameDetails = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        PriorityDetails = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        SeverityDetails = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        StatusDetails = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        DevDetails = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        DateReportedDetails = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        KeywordDetails = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        PostCommentButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        CommentTextArea = new javax.swing.JTextArea();
        CommentBackButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        PatchTestPageID = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        PatchTestPageTitle = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        PatchTestPagePatch = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        PatchTestPageDeveloper = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        PatchTestPageDate = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        PatchTestPageResults = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        PatchTestPageReporter = new javax.swing.JTextField();
        PatchTestPageSubmitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 63, 86));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoutButton.setBackground(new java.awt.Color(29, 29, 29));
        LogoutButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(29, 29, 29));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BugTracker/images/logoff.png"))); // NOI18N
        LogoutButton.setToolTipText("");
        LogoutButton.setBorderPainted(false);
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 70, 60));

        ReportBugButton.setBackground(new java.awt.Color(29, 29, 29));
        ReportBugButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ReportBugButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportBugButton.setText("Report Bug");
        ReportBugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBugButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReportBugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 260, 40));

        BugsWithPatches.setBackground(new java.awt.Color(29, 29, 29));
        BugsWithPatches.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        BugsWithPatches.setForeground(new java.awt.Color(255, 255, 255));
        BugsWithPatches.setText("View Bugs With Patches");
        BugsWithPatches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BugsWithPatchesActionPerformed(evt);
            }
        });
        jPanel1.add(BugsWithPatches, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 260, 40));

        AccountNameField.setBackground(new java.awt.Color(33, 63, 86));
        AccountNameField.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        AccountNameField.setForeground(new java.awt.Color(255, 255, 255));
        AccountNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AccountNameField.setBorder(null);
        AccountNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(AccountNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 280, 50));

        jTextField2.setBackground(new java.awt.Color(33, 63, 86));
        jTextField2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Welcome");
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 40));

        HomeButton1.setBackground(new java.awt.Color(29, 29, 29));
        HomeButton1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        HomeButton1.setForeground(new java.awt.Color(255, 255, 255));
        HomeButton1.setText("Home");
        HomeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(HomeButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 600));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 174, 219));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dashboard");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 237, 83));

        SearchField.setBackground(new java.awt.Color(0, 174, 219));
        SearchField.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        SearchField.setForeground(new java.awt.Color(255, 255, 255));
        SearchField.setText("Search here...");
        SearchField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        SearchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchFieldMouseClicked(evt);
            }
        });
        jPanel2.add(SearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 280, 50));

        jComboBoxSearch.setBackground(new java.awt.Color(0, 174, 219));
        jComboBoxSearch.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jComboBoxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bug ID", "Keyword", "Bug Title", "Assignee", "Reporter" }));
        jPanel2.add(jComboBoxSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 140, 50));

        SearchButton.setBackground(new java.awt.Color(0, 174, 219));
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BugTracker/images/search.png"))); // NOI18N
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 90, 50));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 180));

        ViewBugButton.setBackground(new java.awt.Color(0, 174, 219));
        ViewBugButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ViewBugButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewBugButton.setText("View Details");
        ViewBugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBugButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ViewBugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 140, 40));

        jTable1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bug ID", "Bug Title", "Keyword", "Date", "Description", "Summary", "Reporter", "Assignee", "Developer", "Current Status", "Priority", "Severity", "Patch Submitted", "Reviewer", "Test Results"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 960, 350));

        TestPatchButton.setBackground(new java.awt.Color(0, 174, 219));
        TestPatchButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TestPatchButton.setForeground(new java.awt.Color(255, 255, 255));
        TestPatchButton.setText("Test Patch");
        TestPatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestPatchButtonActionPerformed(evt);
            }
        });
        jPanel3.add(TestPatchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 130, 40));

        jTabbedPane1.addTab("tab1", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Report A Bug");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 320, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Bug Summary");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 160, 30));

        ReportBugTitleField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(ReportBugTitleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 460, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Bug ID");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 210, 30));

        ReportBugIDField.setEditable(false);
        ReportBugIDField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(ReportBugIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 220, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Keyword");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 100, 30));

        ReportBugSummaryField.setColumns(20);
        ReportBugSummaryField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReportBugSummaryField.setLineWrap(true);
        ReportBugSummaryField.setRows(5);
        ReportBugSummaryField.setWrapStyleWord(true);
        ReportBugSummaryField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportBugSummaryFieldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ReportBugSummaryField);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 470, 70));

        ReportBugDescField.setColumns(20);
        ReportBugDescField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReportBugDescField.setLineWrap(true);
        ReportBugDescField.setRows(5);
        ReportBugDescField.setWrapStyleWord(true);
        ReportBugDescField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportBugDescFieldMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ReportBugDescField);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 410, 110));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Issue Description");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 160, 30));

        SubmitBugButton.setBackground(new java.awt.Color(0, 174, 219));
        SubmitBugButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        SubmitBugButton.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBugButton.setText("Submit Bug");
        SubmitBugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBugButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SubmitBugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 500, 140, 50));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("(dd/mm/yyyy)");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 130, 30));

        ReportDateField.setEditable(false);
        ReportDateField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(ReportDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 220, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Bug Title");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 100, 30));

        ReportBugKeywordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel4.add(ReportBugKeywordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 290, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Date");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 70, 30));

        jTabbedPane1.addTab("tab2", jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CommentButton.setBackground(new java.awt.Color(0, 174, 219));
        CommentButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        CommentButton.setForeground(new java.awt.Color(255, 255, 255));
        CommentButton.setText("Comment Section");
        CommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentButtonActionPerformed(evt);
            }
        });
        jPanel5.add(CommentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 190, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Bug Specifications");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 240, 70));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Bug ID");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 70, 30));

        BugIDdetails.setEditable(false);
        BugIDdetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BugIDdetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BugIDdetails.setEnabled(false);
        BugIDdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BugIDdetailsActionPerformed(evt);
            }
        });
        jPanel5.add(BugIDdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 170, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Bug Title");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 80, 30));

        BugTitleDetails.setEditable(false);
        BugTitleDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BugTitleDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BugTitleDetails.setEnabled(false);
        BugTitleDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BugTitleDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(BugTitleDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 270, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Reporter");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 80, 30));

        BugReporterDetails.setEditable(false);
        BugReporterDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BugReporterDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BugReporterDetails.setEnabled(false);
        BugReporterDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BugReporterDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(BugReporterDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 270, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Assignee");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 80, 30));

        AssigneeDetails.setEditable(false);
        AssigneeDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AssigneeDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        AssigneeDetails.setEnabled(false);
        AssigneeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssigneeDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(AssigneeDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 290, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Bug Description");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, 30));

        DescDetails.setEditable(false);
        DescDetails.setColumns(20);
        DescDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DescDetails.setLineWrap(true);
        DescDetails.setRows(5);
        DescDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DescDetails.setEnabled(false);
        jScrollPane3.setViewportView(DescDetails);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 400, 70));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Bug Summary");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 160, 30));

        SumDetails.setEditable(false);
        SumDetails.setColumns(20);
        SumDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SumDetails.setLineWrap(true);
        SumDetails.setRows(5);
        SumDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SumDetails.setEnabled(false);
        jScrollPane4.setViewportView(SumDetails);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 400, 70));

        TestResultsDetails.setEditable(false);
        TestResultsDetails.setColumns(20);
        TestResultsDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TestResultsDetails.setLineWrap(true);
        TestResultsDetails.setRows(5);
        TestResultsDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TestResultsDetails.setEnabled(false);
        jScrollPane10.setViewportView(TestResultsDetails);

        jPanel5.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 400, 70));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Test Results");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 160, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Reviewer");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 110, 30));

        ReviewerDetails.setEditable(false);
        ReviewerDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReviewerDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ReviewerDetails.setEnabled(false);
        ReviewerDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewerDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(ReviewerDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 260, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Submitted Patch");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 110, 30));

        PatchNameDetails.setEditable(false);
        PatchNameDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PatchNameDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PatchNameDetails.setEnabled(false);
        PatchNameDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatchNameDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(PatchNameDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 260, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Priority");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 80, 30));

        PriorityDetails.setEditable(false);
        PriorityDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PriorityDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PriorityDetails.setEnabled(false);
        PriorityDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriorityDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(PriorityDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 210, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Severity");
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 80, 30));

        SeverityDetails.setEditable(false);
        SeverityDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SeverityDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SeverityDetails.setEnabled(false);
        SeverityDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeverityDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(SeverityDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 210, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Curent Status");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 110, 30));

        StatusDetails.setEditable(false);
        StatusDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StatusDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StatusDetails.setEnabled(false);
        StatusDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(StatusDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 210, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Developer");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 80, 30));

        DevDetails.setEditable(false);
        DevDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DevDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DevDetails.setEnabled(false);
        DevDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(DevDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 280, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Date Reported");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 120, 30));

        DateReportedDetails.setEditable(false);
        DateReportedDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DateReportedDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DateReportedDetails.setEnabled(false);
        DateReportedDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateReportedDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(DateReportedDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 180, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Keyword");
        jPanel5.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 80, 30));

        KeywordDetails.setEditable(false);
        KeywordDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        KeywordDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        KeywordDetails.setEnabled(false);
        KeywordDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeywordDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(KeywordDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 270, 30));

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel16.setText("Comments");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 370, 90));

        jTable2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Posted By", "Comments", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable2.setFocusable(false);
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(150);
        jTable2.setSelectionBackground(new java.awt.Color(0, 174, 219));
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jScrollPane6.setViewportView(jTable2);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 930, 340));

        PostCommentButton.setBackground(new java.awt.Color(0, 174, 219));
        PostCommentButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        PostCommentButton.setForeground(new java.awt.Color(255, 255, 255));
        PostCommentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BugTracker/images/Send.png"))); // NOI18N
        PostCommentButton.setText("Post");
        PostCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PostCommentButtonActionPerformed(evt);
            }
        });
        jPanel6.add(PostCommentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 430, 120, 50));

        CommentTextArea.setColumns(20);
        CommentTextArea.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        CommentTextArea.setLineWrap(true);
        CommentTextArea.setRows(5);
        CommentTextArea.setWrapStyleWord(true);
        CommentTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CommentTextAreaMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(CommentTextArea);

        jPanel6.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 780, 110));

        CommentBackButton.setBackground(new java.awt.Color(0, 174, 219));
        CommentBackButton.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        CommentBackButton.setForeground(new java.awt.Color(255, 255, 255));
        CommentBackButton.setText("Back");
        CommentBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentBackButtonActionPerformed(evt);
            }
        });
        jPanel6.add(CommentBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 120, 50));

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel24.setText("Input Patch Test Results");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 380, 90));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Bug ID");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 70, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Bug Title");
        jPanel7.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, 30));

        PatchTestPageID.setEditable(false);
        PatchTestPageID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel7.add(PatchTestPageID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 30));

        PatchTestPageTitle.setEditable(false);
        PatchTestPageTitle.setColumns(20);
        PatchTestPageTitle.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PatchTestPageTitle.setRows(5);
        jScrollPane8.setViewportView(PatchTestPageTitle);

        jPanel7.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 420, 40));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Input Testing Results");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 30));

        PatchTestPagePatch.setEditable(false);
        PatchTestPagePatch.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel7.add(PatchTestPagePatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 250, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Developer ");
        jPanel7.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 130, 30));

        PatchTestPageDeveloper.setEditable(false);
        PatchTestPageDeveloper.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel7.add(PatchTestPageDeveloper, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 280, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Date Reported");
        jPanel7.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 160, 30));

        PatchTestPageDate.setEditable(false);
        PatchTestPageDate.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel7.add(PatchTestPageDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 240, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Patch Submitted");
        jPanel7.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, 30));

        PatchTestPageResults.setColumns(20);
        PatchTestPageResults.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        PatchTestPageResults.setLineWrap(true);
        PatchTestPageResults.setRows(5);
        PatchTestPageResults.setWrapStyleWord(true);
        jScrollPane9.setViewportView(PatchTestPageResults);

        jPanel7.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 460, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Reporter ");
        jPanel7.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 160, 30));

        PatchTestPageReporter.setEditable(false);
        PatchTestPageReporter.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel7.add(PatchTestPageReporter, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 240, 30));

        PatchTestPageSubmitButton.setBackground(new java.awt.Color(0, 174, 219));
        PatchTestPageSubmitButton.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        PatchTestPageSubmitButton.setForeground(new java.awt.Color(255, 255, 255));
        PatchTestPageSubmitButton.setText("Submit Test");
        PatchTestPageSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatchTestPageSubmitButtonActionPerformed(evt);
            }
        });
        jPanel7.add(PatchTestPageSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 130, 40));

        jTabbedPane1.addTab("tab5", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -30, 980, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void patchedBugs()
    {
        java.awt.event.ActionEvent evt = null;
        BugsWithPatchesActionPerformed(evt);
    }
    
    public void testPatchButton()
    {
        java.awt.event.ActionEvent evt = null;
        TestPatchButtonActionPerformed(evt);
    }
    public void submitButton()
    {
        java.awt.event.ActionEvent evt = null;
        PatchTestPageSubmitButtonActionPerformed(evt);
    }
    
    public void displayHP()
    {
        DisplayHomePage();
    }
    
    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        // TODO add your handling code here:
        //int input = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?");
        //if(input == 0)
        dispose();
        
        LogoutUI LUI = new LogoutUI();
        LUI.LogoutButtonActionPerformed();
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void SearchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchFieldMouseClicked
        // TODO add your handling code here:
        SearchField.setText(null);
        //clear selection from main table
        jTable1.getSelectionModel().clearSelection();
    }//GEN-LAST:event_SearchFieldMouseClicked

    private void BugsWithPatchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BugsWithPatchesActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        //clear selection from main table
        jTable1.getSelectionModel().clearSelection();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try
	{	
	    FileReader in = new FileReader("BugReport.txt");
            BufferedReader br = new BufferedReader(in);
            // Read files
            String readLine = "";
            while ((readLine = br.readLine()) != null) 
            {
                String [] row = readLine.split(":");
                if(row[9].equals("Pending"))
                    model.addRow(row);
            }	
            br.close();
            in.close();
	} 
	catch (IOException ex) {
            Logger.getLogger(DeveloperUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BugsWithPatchesActionPerformed

    // switches to Report bug page and auto fills current date 
    // and generates bug id
    
    private void DisplayReportPage()
    {
        jTabbedPane1.setSelectedIndex(1);
    }
    private void DisplayHomePage()
    {
        jTabbedPane1.setSelectedIndex(0);
    }
    
    private void ReportBugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBugButtonActionPerformed
        // TODO add your handling code here:
        //clear selection from main table
        jTable1.getSelectionModel().clearSelection();
        String pattern = "dd/MM/yyyy";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        String date = simpleDateFormat.format(new Date());
        String id = "";
        ReportDateField.setText(date);
        
        //generate bug id
        try
	{	
            File myObj = new File("BugReport.txt");
            Scanner myReader = new Scanner(myObj);
			
            // Read files
            while (myReader.hasNextLine()) 
            {
		String readLine = myReader.nextLine();
		String [] splitLine = readLine.split(":");
                id = splitLine[0];
            }	
            myReader.close();
	} 
		
	// Catch error
	catch (FileNotFoundException e) 
	{
            System.out.println("An error occurred.");
            e.printStackTrace();
        }
        if(id.equals(""))
        {
            int number = 10000;
            id = Integer.toString(number);
        }
        else
        {
            int number = Integer.parseInt(id);
            number++;
            id = Integer.toString(number);
        }
        ReportBugIDField.setText(id);
        DisplayReportPage();
    }//GEN-LAST:event_ReportBugButtonActionPerformed

    private void ViewBugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBugButtonActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "No bug was selected from the list!","Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            jTabbedPane1.setSelectedIndex(2);
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int i = jTable1.getSelectedRow();
            String [] array = new String[15];
            for(int j = 0; j < 15; j++)
            {
                array[j] = model.getValueAt(i, j).toString();
            }
            setDataDetailsPage(array);
            jTabbedPane1.setSelectedIndex(2);
        }
    }//GEN-LAST:event_ViewBugButtonActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        String searchParam = jComboBoxSearch.getSelectedItem().toString();
        String searchText = SearchField.getText();
        SearchBugKeywordController SBK = new SearchBugKeywordController();
        String [] array = SBK.getSearchData(bugReportList, searchParam, searchText);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        for(int i = 0; i < array.length; i++)
        {
            String [] splitArr = array[i].split(":");
            model.addRow(splitArr);
        }
    }//GEN-LAST:event_SearchButtonActionPerformed
    
    private void CommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        //load comments
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
        String bugid = model1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        //change filepath here
        String filepath = "bug"+bugid+".txt";
        user.loadComments(filepath, model);
        jTable2.setDefaultRenderer(Object.class, new MultilineTableCellRenderer());
        jTable2.setModel(model);
    }//GEN-LAST:event_CommentButtonActionPerformed

    public void setTable1Settings()
    {
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(400);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(13).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(14).setPreferredWidth(200);
        jTable1.setRowSelectionAllowed(true);
        //table 2
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(650);
        jTable2.getColumnModel().getColumn(2).setMinWidth(100);
        jTable2.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        //header of both table
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new Color(0,174,219));
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        for (int i = 0; i < jTable1.getModel().getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        for (int i = 0; i < jTable2.getModel().getColumnCount(); i++) {
            jTable2.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
    }
    
    // for comments
    private void PostCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PostCommentButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        DefaultTableModel model1 = (DefaultTableModel)jTable1.getModel();
        String bugid = model1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        //change file path here
        String filepath = "bug"+bugid+".txt";
        String pattern = "dd/MM/yyyy HH:mm";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        String comments = CommentTextArea.getText();
        //encasing string in html for line breaks
        //update not using this code because found better solution
//        String modifiedComment = "<html>";
//        String[] splited = comments.split("\\s+");
//        for(int i = 0; i < splited.length; i++)
//        {
//            modifiedComment += splited[i];
//            modifiedComment += " ";
//            if(i % 9 == 0 && i != 0)
//                modifiedComment += "<br>";
//            
//        }
//        modifiedComment += "</html>";
        String nameid = name + " - "+id;
        String date = simpleDateFormat.format(new Date());
        String [] array = {nameid, comments, date};
        boolean success = user.updateCommentsData(filepath, array);
        model.addRow(new Object[]{nameid, comments, date});
        jTable2.setDefaultRenderer(Object.class, new MultilineTableCellRenderer());
        CommentTextArea.setText("");
    }//GEN-LAST:event_PostCommentButtonActionPerformed

    private void CommentTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CommentTextAreaMouseClicked
        // TODO add your handling code here:
        CommentTextArea.setLineWrap(true);
        CommentTextArea.setWrapStyleWord(true);
        CommentTextArea.setToolTipText("Type your comment");
    }//GEN-LAST:event_CommentTextAreaMouseClicked

    private void CommentBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentBackButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        CommentTextArea.setText("");
        model.setRowCount(0);
    }//GEN-LAST:event_CommentBackButtonActionPerformed
    
    //set text fields in details page
    public void setDataDetailsPage(String [] array)
    {
        //set text for all fields in bug description page
        BugIDdetails.setText(array[0]);
        BugTitleDetails.setText(array[1]);
        KeywordDetails.setText(array[2]);
        DateReportedDetails.setText(array[3]);
        DescDetails.setText(array[4]);
        SumDetails.setText(array[5]);
        BugReporterDetails.setText(array[6]);
        AssigneeDetails.setText(array[7]);
        DevDetails.setText(array[8]);
        StatusDetails.setText(array[9]);
        SeverityDetails.setText(array[10]);
        PriorityDetails.setText(array[11]);
        PatchNameDetails.setText(array[12]);
        ReviewerDetails.setText(array[13]);
        TestResultsDetails.setText(array[14]);
    }
    
    // gets all bug values entered from the text fields entered
    // stores them in array first write in text file then update in main table
    private void SubmitBugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBugButtonActionPerformed
        // TODO add your handling code here:
         //get text from all fields from report bug page.
        String [] array = new String[jTable1.getColumnCount()];  //declare array
        array[0] = ReportBugIDField.getText();          // id
        array[1] = ReportBugTitleField.getText();       // title
        array[2] = ReportBugKeywordField.getText();     // keyword
        array[3] = ReportDateField.getText();           // date
        array[4] = ReportBugDescField.getText();        // description
        array[5] = ReportBugSummaryField.getText();     // summary
        array[6] = name+" - "+id;                       // reporter name
        array[7] = "null";                                // assignee
        array[8] = "null";                                // assigned developer
        array[9] = "not resolved";                      // current status
        array[10] = "null";                               // assigned severity
        array[11] = "null";                               // assigned priority
        array[12] = "null";                               //patch submitted
        array[13] = "null";                              // test results
        array[14] = "null";                              // Tester
        
        ReportBugController RBC = new ReportBugController();
        
        if(RBC.ValidateFields(array))
        {
            BugReport bug = new BugReport();
            bug.setBugData(array);
            boolean success = bug.SaveReportedBug(array);
            if(success)
            {
                //update in main table
                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                model.addRow(array);
                DisplayHomePage();
                setDataDetailsPage(array);
                //set report bug page fields to empty values;
                ReportBugTitleField.setText("");       // title
                ReportBugKeywordField.setText("");     // keyword
                ReportBugDescField.setText("");        // description
                ReportBugSummaryField.setText("");     //summary
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Fields cannot be empty!","Report Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SubmitBugButtonActionPerformed

    private void AccountNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccountNameFieldActionPerformed

    private void ReportBugDescFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportBugDescFieldMouseClicked
        // TODO add your handling code here:
        ReportBugDescField.setLineWrap(true);
        ReportBugDescField.setWrapStyleWord(true);
    }//GEN-LAST:event_ReportBugDescFieldMouseClicked

    private void ReportBugSummaryFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportBugSummaryFieldMouseClicked
        // TODO add your handling code here:
        ReportBugDescField.setLineWrap(true);
        ReportBugDescField.setWrapStyleWord(true);
    }//GEN-LAST:event_ReportBugSummaryFieldMouseClicked

    //when bug is selected in main table it switches field values
    // in view details page
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        //clear selection from main table
        jTable1.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        //clear selection from main table
        jTable1.getSelectionModel().clearSelection();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void HomeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        user.readBugList(model, bugReportList);
        jTabbedPane1.setSelectedIndex(0);
        jTable1.getSelectionModel().clearSelection();
    }//GEN-LAST:event_HomeButton1ActionPerformed

    private void TestPatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestPatchButtonActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(null, "No bug was selected from the list!","Unsuccessful", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            //Set Text field values
            DefaultTableModel tModel = (DefaultTableModel)jTable1.getModel();
            int index = jTable1.getSelectedRow();
            PatchTestPageID.setText(tModel.getValueAt(index, 0).toString());
            PatchTestPageTitle.setText(tModel.getValueAt(index, 1).toString());
            PatchTestPageDate.setText(tModel.getValueAt(index, 3).toString());
            PatchTestPageReporter.setText(tModel.getValueAt(index, 6).toString());
            PatchTestPageDeveloper.setText(tModel.getValueAt(index, 8).toString());
            PatchTestPagePatch.setText(tModel.getValueAt(index, 12).toString());
            String testResult = tModel.getValueAt(index, 14).toString();
            if(testResult.equals("null"))
                PatchTestPageResults.setText("");
            else
                PatchTestPageResults.setText(tModel.getValueAt(index, 14).toString());
            jTabbedPane1.setSelectedIndex(4);
        }
    }//GEN-LAST:event_TestPatchButtonActionPerformed

    public void updateTestResult(TestResult tr, String bugid)
    {
        BugReport br = new BugReport();
        br.saveTestResultData(tr, bugid);
    }
    
    private void PatchTestPageSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatchTestPageSubmitButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        String testResult = PatchTestPageResults.getText();
        String bugid = PatchTestPageID.getText();
        TestResult tr = new TestResult();
        tr.SetTestResult(testResult);
        String tester = name + " - " + id;
        tr.setTester(tester);
        updateTestResult(tr, bugid);
        user.readBugList(model, bugReportList);
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_PatchTestPageSubmitButtonActionPerformed

    private void BugIDdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BugIDdetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BugIDdetailsActionPerformed

    private void BugTitleDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BugTitleDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BugTitleDetailsActionPerformed

    private void BugReporterDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BugReporterDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BugReporterDetailsActionPerformed

    private void AssigneeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssigneeDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AssigneeDetailsActionPerformed

    private void ReviewerDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewerDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReviewerDetailsActionPerformed

    private void PatchNameDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatchNameDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatchNameDetailsActionPerformed

    private void PriorityDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriorityDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriorityDetailsActionPerformed

    private void SeverityDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeverityDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeverityDetailsActionPerformed

    private void StatusDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StatusDetailsActionPerformed

    private void DevDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DevDetailsActionPerformed

    private void DateReportedDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateReportedDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateReportedDetailsActionPerformed

    private void KeywordDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeywordDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KeywordDetailsActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewerUI(name, id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNameField;
    private javax.swing.JTextField AssigneeDetails;
    private javax.swing.JTextField BugIDdetails;
    private javax.swing.JTextField BugReporterDetails;
    private javax.swing.JTextField BugTitleDetails;
    private javax.swing.JButton BugsWithPatches;
    private javax.swing.JButton CommentBackButton;
    private javax.swing.JButton CommentButton;
    private javax.swing.JTextArea CommentTextArea;
    private javax.swing.JTextField DateReportedDetails;
    private javax.swing.JTextArea DescDetails;
    private javax.swing.JTextField DevDetails;
    private javax.swing.JButton HomeButton1;
    private javax.swing.JTextField KeywordDetails;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JTextField PatchNameDetails;
    private javax.swing.JTextField PatchTestPageDate;
    private javax.swing.JTextField PatchTestPageDeveloper;
    private javax.swing.JTextField PatchTestPageID;
    private javax.swing.JTextField PatchTestPagePatch;
    private javax.swing.JTextField PatchTestPageReporter;
    private javax.swing.JTextArea PatchTestPageResults;
    private javax.swing.JButton PatchTestPageSubmitButton;
    private javax.swing.JTextArea PatchTestPageTitle;
    private javax.swing.JButton PostCommentButton;
    private javax.swing.JTextField PriorityDetails;
    private javax.swing.JButton ReportBugButton;
    private javax.swing.JTextArea ReportBugDescField;
    private javax.swing.JTextField ReportBugIDField;
    private javax.swing.JTextField ReportBugKeywordField;
    private javax.swing.JTextArea ReportBugSummaryField;
    private javax.swing.JTextField ReportBugTitleField;
    private javax.swing.JTextField ReportDateField;
    private javax.swing.JTextField ReviewerDetails;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField SeverityDetails;
    private javax.swing.JTextField StatusDetails;
    private javax.swing.JButton SubmitBugButton;
    private javax.swing.JTextArea SumDetails;
    private javax.swing.JButton TestPatchButton;
    private javax.swing.JTextArea TestResultsDetails;
    private javax.swing.JButton ViewBugButton;
    private javax.swing.JComboBox jComboBoxSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public class TextTableAlign extends DefaultTableCellRenderer {
        
        @Override
        public Component getTableCellRendererComponent(JTable table,Object value, 
                boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            setHorizontalAlignment(SwingConstants.LEFT);
            return this;
        }

    }
    public class MultilineTableCellRenderer extends JTextArea
    implements TableCellRenderer {
        private List<List<Integer>> rowColHeight = new ArrayList<>();
        private static final int MAX_LEN = 150;

        public MultilineTableCellRenderer() {
            setLineWrap(true);
            setWrapStyleWord(true);
        }

        @Override
        public Component getTableCellRendererComponent(
                JTable table, Object value, boolean isSelected, boolean hasFocus,
                int row, int column) {
            //cell backgroud color when selected
            if (isSelected) {
                this.setBackground(new Color(102,153,255));
                this.setForeground(Color.WHITE);
            } else {
                this.setBackground(UIManager.getColor("Table.background"));
                this.setForeground(Color.BLACK);
            }

            setFont(table.getFont());
            if (value != null) {
                setText(value.toString());
            } else {
                setText("");
            }
            adjustRowHeight(table, row, column);
            this.setBorder (BorderFactory.createBevelBorder (EtchedBorder.RAISED));
            return this;
        }

        /**
         * Calculate the new preferred height for a given row, and sets the height on the table.
         */
        private void adjustRowHeight(JTable table, int row, int column) {
            //The trick to get this to work properly is to set the width of the column to the
            //textarea. The reason for this is that getPreferredSize(), without a width tries
            //to place all the text in one line. By setting the size with the with of the column,
            //getPreferredSize() returnes the proper height which the row should have in
            //order to make room for the text.
            int cWidth = table.getTableHeader().getColumnModel().getColumn(column).getWidth();
            setSize(new Dimension(cWidth, 1000));
            int prefH = getPreferredSize().height;
            while (rowColHeight.size() <= row) {
                rowColHeight.add(new ArrayList<Integer>(column));
            }
            List<Integer> colHeights = rowColHeight.get(row);
            while (colHeights.size() <= column) {
                colHeights.add(0);
            }
            colHeights.set(column, prefH);
            int maxH = prefH;
            for (Integer colHeight : colHeights) {
                if (colHeight > maxH) {
                    maxH = colHeight;
                }
            }
            if (table.getRowHeight(row) != maxH) {
                table.setRowHeight(row, maxH);
            }
        }
    }
}
